add explainer
w3c/vc-status-list-2021 pull request #75
Opened 2023-07-03 11:18 UTC by mkhraisha

Adds an explainer for TAG #72

2023-07-03 12:03 UTC, mkhraisha commented
not sure why CI is failing on this and #76

2023-07-06 15:03 UTC, TallTed requested changes
The usual language tweaks for clarity

2023-07-06 15:03 UTC, TallTed commented on explainer.md
> +2. The use of content distribution networks by issuers can increase the privacy of holders by reducing or eliminating requests for the status lists from the issuer. Often, a request for a revocation
```suggestion
* It is possible for verifiers to increase the privacy of holders whose verifiable credentials are being checked by caching status lists that have been fetched from remote servers. By caching the content locally, less correlatable information can be inferred from verifier-based access patterns on the status list.
* The use of content distribution networks (CDNs) by issuers can increase the privacy of holders by reducing or eliminating requests for the status lists directly from the issuer. Often, a request for a revocation list can be served by an edge device and thus be faster and reduce the load on the server, as well as cloaking verifiers and holders from issuers.
```

2023-07-09 17:02 UTC, mkhraisha commented
Merged in comments

2023-07-20 14:06 UTC, msporny commented on explainer.md
> +At the most basic level, status information for all verifiable credentials issued by an issuer are expressed as simple binary values. The issuer keeps a bitstring list of all verifiable credentials i
This is no longer accurate as of PR #65.

2023-07-20 14:09 UTC, msporny approved these changes

2023-07-20 14:09 UTC, merged